# build machine needs Chromium, Chromium Chrome Driver

trigger:
- master

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: default
    displayName: 'Default'

    pool: Default

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: 'Install NPM dependencies'

    - script: npm run lint
      displayName: 'Lint'

    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'sonarcloud-escalonn'
        organization: '1902-feb18-net'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '1904-ng-card'
        cliSources: 'src'
        extraProperties: |
          sonar.typescript.lcov.reportPaths=artifacts/test/coverage/*.lcov
      displayName: 'Prepare SonarCloud analysis'

    - script: npm run build:ci
      displayName: 'Build'

    - script: npm run test:ci
      displayName: 'Run unit tests'

    - task: SonarCloudAnalyze@1
      displayName: 'Run SonarCloud analysis'

    - task: SonarCloudPublish@1
      displayName: 'Publish SonarCloud quality gate result'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go(0518cd5b-d389-4983-9496-cdcae31dcc60)'
        appType: 'webApp'
        WebAppName: '1904-ng-card'
        packageForLinux: 'dist/angular-demo'
      displayName: 'Deploy to Azure App Service'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist/angular-demo'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish build artifact'
